apiVersion: v1 
kind: ConfigMap
metadata:
  name: mysql-env
data:
  MYSQL_DATABASE: students

---

apiVersion: v1 
kind: Secret
metadata:
  name: mysql-env-secret
type: opaque
data:
  MYSQL_ROOT_PASSWORD: UGFzc3dvcmQxMjMK
  MYSQL_USER: YWRtaW4K
  MYSQL_PASSWORD: UGFzc3dvcmQxMjMK
