apiVersion: v1 
kind: ConfigMap
metadata:
  name: mysql-env
  namespace: nginx-php-mysql-pro
data:
  MYSQL_DATABASE: students

---

apiVersion: v1 
kind: Secret
metadata:
  name: mysql-env-secret
  namespace: nginx-php-mysql-pro
type: opaque
data:
  MYSQL_ROOT_PASSWORD: UGFzc3dvcmQxMjM=
  MYSQL_USER: YWRtaW4=
  MYSQL_PASSWORD: UGFzc3dvcmQxMjM=
