apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-php-deployment
  labels:
    tag: nginx-php-deployment
spec:
  selector:
    matchLabels:
      tag: nginx-php-frontend
    
  template:
    metadata:
      name: nginx-php-app
      labels:
        tag: nginx-php-frontend
    spec:
      containers:
        - name: nginx-php-image
          image: abdulp07/nginx-php:V12
  replicas: 3

---

apiVersion: v1 
kind: Service
metadata:
  name: nginx-php-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    tag: nginx-php-frontend
    
    
